### ISSUE TITLE
missing git tag

### ISSUE THREAD

**Issue by glensc** [tracboat/tracboat#1]
https://pypi.python.org/pypi/tracboat has 0.0.1 released
it should be tagged in git with same version 0.0.1
but none published as of now: https://github.com/nazavode/tracboat/releases

**Comment by nazavode** [comment]
You're right, this project is still in a somewhat alpha state, I'm fixing a lot of serious bugs in the dev branch. I'm thinking about removing the pypi package until the codebase reaches a more stable state, but I would like to have some feedback. What do you think?

**Comment by nazavode** [comment]
p.s.: @glensc  mentioned you in the AUTHORS file, thanks for the PR

**Comment by glensc** [comment]
if you remove the published pypi package, that's one way to solve the inconsistency. i have no opinion here.

ps: i used git clone and virtualenv.

**Comment by nazavode** [comment]
Got it, I think the package should be removed until we reach a more usable release.

**Comment by nazavode** [comment]
Ok, package removed from pypi, it was actually polluting the package index.
