### ISSUE TITLE
Error in gitlab 9.3.5 version data model

### ISSUE THREAD

**Issue by ivanelson** [tracboat/tracboat#29]
Hi,
TracebacDoes the current version support the gitlab version 9.3.5 data model?

It looks like an error in the model:

> Traceback (most recent call last):
>   File "/home/ivan/tracboat/VENV/bin/tracboat", line 11, in <module>
>     load_entry_point('tracboat', 'console_scripts', 'tracboat')()
>   File "/home/ivan/tracboat/src/tracboat/cli.py", line 423, in main
>     cli(obj={})  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/ivan/tracboat/src/tracboat/cli.py", line 118, in wrapper
>     return func(*args, **kwargs)
>   File "/home/ivan/tracboat/src/tracboat/cli.py", line 168, in wrapper
>     return func(*args, **kwargs)
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/ivan/tracboat/src/tracboat/cli.py", line 413, in migrate
>     userattrs=userattrs,
>   File "/home/ivan/tracboat/src/tracboat/migrate.py", line 280, in migrate
>     gitlab.create_user(**attrs)
>   File "/home/ivan/tracboat/src/tracboat/gitlab/direct.py", line 182, in create_user
>     user = M.Users.get(M.Users.email == email)
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 4916, in get
>     return sq.get()
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 3171, in get
>     return next(clone.execute())
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 3223, in execute
>     self._qr = ResultWrapper(model_class, self._execute(), query_meta)
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 2902, in _execute
>     return self.database.execute_sql(sql, params, self.require_commit)
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 3765, in execute_sql
>     self.commit()
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 3588, in __exit__
>     reraise(new_type, new_type(*exc_args), traceback)
>   File "/home/ivan/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 3758, in execute_sql
>     cursor.execute(sql, params or ())
> peewee.ProgrammingError: column t1.authorized_projects_populated does not exist
> LINE 1: ...."id", "t1"."admin", "t1"."authentication_token", "t1"."auth..

**Comment by nazavode** [comment]
Wow, they are pushing new versions like crazy :) Yes, the latest version supported is 9.0.0, I need to generate models for new versions.

**Comment by ivanelson** [comment]
I generated a [1] model based on this project: https://github.com/moimael/trac-to-gitlab

And I changed the module cli.py to:
```
@click.option(
        '--gitlab-version',
        default='9.3.5',
        show_default=True,
        help='GitLab target version',
    )

```
[1] model:

`$ pwiz.py -e postgresql -u gitlab gitlabhq_production > gitlab_direct/model<version>.py`

I'm testing.

**Comment by nazavode** [comment]
Cheers, feel free to open a pull request. Anyway I planned to add a specific subcommand to generate new models even if I still have to figure out how to write it neatly.

**Comment by ivanelson** [comment]
Hi,

I was able to migrate using the method quoted in my previous comment.

With some caveats:

Critical problems:
1. The "name" column was empty or null in the "users" table.
2. The "e-mail" column contained the user name instead of the e-mail account. It looks like there was a reversal of data between the "name" and "email" columns.
3. In the Gitlab "issues" table, the "iid" column is null.

These errors prevent the GitLab instance from working. Returns errors: 500, 502, 422.

Less relevant:
1. "UnicodeEncodeError 'ascii' codec can not encode character", If in the milestone name you have characters with an accent(Sample: Migração). In my case, I changed the trac.py module to not migrate the milestone.

Anyone who wants to venture into these with the boat saves lives, should be aware of this, as it is at risk of shipwreck.

Especially, if a novice in gitlab.
:)

**Comment by glensc** [comment]
i always end up getting access error from postgresql if i don't use some gitlab user. so i sudo to "git"

```
# sudo -H -u git pwiz.py -u gitlab gitlabhq_production > src/tracboat/gitlab/model/model93.py
```

how do others solve this issue? i tried to configure pgsql hba.conf but still no luck

**Comment by ivanelson** [comment]
Hi,

Creates a mapping between the S.O user and the gitlab user within the pg_ident.conf file
Example:

# MAPNAME       SYSTEM-USERNAME         PG-USERNAME
gitlab                   git                                          gitlab
gitlab                   mattermost                            gitlab_mattermost
**gitlab                   my_user_in_so                      gitlab**
