### ISSUE TITLE
Plan to support GitLab 11?

### ISSUE THREAD

**Issue by cyrosy** [tracboat/tracboat#47]
Do you have any plan to support migration towards an up-to-date GitLab instance? (currently 11.0 or 11.1)

**Comment by glensc** [comment]
If you have problem, then open issue with details.

the model updates aren't much relevant: https://github.com/tracboat/tracboat/pull/36

**Comment by cyrosy** [comment]
Thanks for the quick update, I'll test on the latest version and let you know if everything works.
Maybe you could add a note in the README with the supported GitLab versions ?

**Comment by glensc** [comment]
https://github.com/tracboat/tracboat/commit/942b2e66cd4a4cc96d26cfb6a18ed6be82095832
